### ISSUE TITLE
Add option to set the "Range" header when proxying a RTSP stream

### ISSUE THREAD

**Issue by aler9** [aler9/mediamtx#1096]
## Describe the feature

Add option to set the "Range" header when proxying a RTSP stream, i.e.

```yml
paths:
  server:
    source: rtsp://myserver
    rtspRange: 15.0-30.0
```

This allows to seek on-demand streams.
