### ISSUE TITLE
Add option to set listening address family

### ISSUE THREAD

**Issue by aler9** [aler9/mediamtx#1665]
## Describe the feature

This allows to stop listening on IPv6 as requested in #1385

Prototype:

```yml
# whether to use IPv4, IPv6 or both.
addressFamily: any|ipv4|ipv6
```

**Comment by aler9** [comment]
@pikachu937 in the end i didn't add an option, but hacked the server in order to listen on IPv4 only when listen IP is 0.0.0.0. This is the only one problematic IP, while in every other case the server listen only on the address family of the listen IP.

**Comment by pikachu937** [comment]
i checked and this work only if set in config file ip address and port - 0.0.0.0:55544
```yaml
rtspDisable: no
protocols: [udp, tcp]
encryption: "no"
rtspAddress: 0.0.0.0:55544
rtpAddress: 0.0.0.0:22222
rtcpAddress: 0.0.0.0:22223
```
but, this is does not work if set in config file only port :55544(by default in config file)
```yaml
rtspDisable: no
protocols: [udp, tcp]
encryption: "no"
rtspAddress: :55544
rtpAddress: :22222
rtcpAddress: :22223
```
can you make it automatically detect and not have to set a separate IP address?
