### ISSUE TITLE
Error to read HLS in ondemand mode from RTSP H.265 source

### ISSUE THREAD

**Issue by timerlan** [aler9/mediamtx#1695]
## Which version are you using?

v0.22.0

## Which operating system are you using?

- [ ] Linux amd64 standard
- [x] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Try to convert RTSP H.265 stream from HikVision to HLS in OnDemand mode. After open browser i have error 404 to open `/stream502/init.mp4`

Google Chrome log
```
GET 200 /stream502/index.m3u8
GET 200 /stream502/stream.m3u8
GET 404 /stream502/init.mp4
```

HLS config
```
hlsDisable: no
hlsAddress: :8888
hlsEncryption: no
hlsServerKey: server.key
hlsAlwaysRemux: no
hlsVariant: fmp4
hlsSegmentCount: 7
hlsSegmentDuration: 1s
hlsPartDuration: 200ms
hlsSegmentMaxSize: 50M
hlsAllowOrigin: '*'
hlsTrustedProxies: []
```
Config source config 

````
paths:
  stream502:
    source: rtsp://login:password@192.168.0.5:554/ISAPI/Streaming/Channels/502
    sourceProtocol: tcp
    sourceAnyPortEnable: no
    sourceOnDemand: yes
    sourceOnDemandStartTimeout: 60s
    sourceOnDemandCloseAfter: 10s
    disablePublisherOverride: no
    runOnInitRestart: no
    runOnDemandRestart: no
    runOnDemandStartTimeout: 60s
    runOnDemandCloseAfter: 10s
    runOnReadyRestart: no
    runOnReadRestart: no

````

## Describe how to replicate the issue

1. start the server
2. read stream from video recorder
3. open in Google Chrome

## Did you attach the server logs?

yes
