### ISSUE TITLE
RTSP/WebRTC Stream Freezing

### ISSUE THREAD

**Issue by NestorWetter** [aler9/mediamtx#1697]
## Which version are you using?

v0.22.0

## Which operating system are you using?

- [ ] Linux amd64 standard
- [x] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

We're trying to stream a screen capture from a windows VM in Azure. We use ffmpeg and gdigrab to capture the desktop content and send it over rtsp to an rtsp-simple-server running on docker in another VM (also on azure). When we then try to view the stream using the built-in WebRTC player, the stream mostly works, but it periodically freezes. It usually freezes for 5-10s at least every 2 minutes. Is there perhaps a way to reduce this? Or do you know how we could analyze this further? Any help you can provide would be greatly appreciated :)

## Describe how to replicate the issue

1. set up two VMs:
  - Windows-VM:/home/wetter/Work/remote-control/RemoteControl/poc/rtsp-simple-server-poc/github-issue/diff.yml
    - Azure "Standard D4s v3 (4 vcpus, 16 GiB memory)"
    - Windows Server 2022 Datacenter Azure Edition
  - Ubuntu-VM:
    - Standard DS3 v2 (4 vcpus, 14 GiB memory) 
    - Ubuntu 22.04
2. Start RTSP Simple Server with the following docker compose config and server configuration:
  - docker-compose.yaml
    ```
    version: '3.8'
    services:
    rtsp-simple-proxy:
        image: aler9/rtsp-simple-server:latest
        # networks:
        #  - original
        volumes:
        - /home/azure_user/video-proxy/mount:/mount
        - /home/azure_user/video-proxy/config/rtsp-simple-server.yml:/rtsp-simple-server.yml
        restart: always
        ports:
            - 8554:8554
            - 1935:1935
            - 8888:8888
            - 8889:8889
            - 8189:8189
            - 8322:8322
        expose:
        - 8554
        - 8322
        - 1935
        - 8888
        - 8889
        - 8189
    ```
  - rtsp-simple-server.yml (these are just the differences to the default values):
    ``` 
    # Timeout of read operations.
    readTimeout: 40s
    # Timeout of write operations.
    writeTimeout: 40s
    protocols: [tcp]
    hlsEncryption: yes
    #### hlsServerKey: server.key
    hlsServerKey: ./mount/server.key
    # Path to the server certificate.
    #### hlsServerCert: server.crt
    hlsServerCert: ./mount/server.crt
    hlsAlwaysRemux: yes
    hlsSegmentDuration: 300ms
    hlsPartDuration: 100ms
    paths:
      all:
        # If sourceOnDemand is "yes", readers will be put on hold until the source is
        # ready or until this amount of time has passed.
        sourceOnDemandStartTimeout: 40s
        # If sourceOnDemand is "yes", the source will be closed when there are no
        # readers connected and this amount of time has passed.
        sourceOnDemandCloseAfter: 40s
        rpiCameraDenoise: 'off'
        # Readers will be put on hold until the runOnDemand command starts publishing
        # or until this amount of time has passed.
        runOnDemandStartTimeout: 40s
        # The command will be closed when there are no
        # readers connected and this amount of time has passed.
        runOnDemandCloseAfter: 40s
    ```
3. Start FFMPEG stream with following command:
  - `ffmpeg -r 10 -f gdigrab -i desktop -pix_fmt yuv420p -vcodec libx264 -b:v 1024k -maxrate 2058k -bufsize 2058k -profile:v main -preset ultrafast -tune zerolatency -bf 0 -f rtsp rtsps://<SOMEUSER>:<SOMEPASSWORD>@<UBUNTU_VM_IP>:8322/<STREAM_NAME>`
4. View Stream at WebRTC address and wait for freezing
  - `https://<UBUNTU_VM_IP>:8889/<STREAM_NAME>/`
  - Freezing seems more common when the streamed video is more dynamic (like a video with changing scenes)

## Did you attach the server logs?

yes
[shortlogs.txt](https://github.com/aler9/mediamtx/files/11218833/shortlogs.txt)

## Did you attach a network dump?

no, we did analyze the network traffic with wireshark, but found no changes in the traffic as the freezes were occurring. If its still necessary we can still find the tcpdump and provide it here.
