### ISSUE TITLE
runOnDemand stops due to Broken pipe

### ISSUE THREAD

**Issue by jemershaw** [aler9/mediamtx#717]
## Which version are you using?

v0.17.9

## Which operating system are you using?
- [x] Linux amd64 Docker

## Describe the issue

Description
I am running about 5 ip cameras(wyze, reolink, and eufy) and randomly I will receive an error like `Error writing trailer of rtsp://localhost:8554/camera1: Broken pipe` and then the ondemand endpoint stops serving. I also have `runOnDemandRestart: yes` set but when the process dies it doesn't restart. I can't seem to figure out what is causing the ffmpeg process to exist but it should just restart the process. When the process does die and doesn't restart I tried to run the command manually from the container and it says the endpoint is not available even though there's other endpoints that are actively serving content. I thought the `runOnDemandRestart` wasn't working so I wrapped the command in a `while` loop and it still somehow exited -- I'm unclear what is actually killing the process.

Here are the two commands I tried but both still seem to bail out for unknown reason.
```
paths:
  camera1:
    runOnDemand: ffmpeg -hide_banner -loglevel error -avoid_negative_ts make_zero -fflags +genpts+nobuffer -flags low_delay -rtsp_transport tcp -use_wallclock_as_timestamps 1 -f rtsp -stimeout 5000000 -i rtsp://$USER:$PASSWORD@$CAMERA1:554/live0 -filter:a volume=10.0 -map 0:v -c:v:0 copy -map 0:a:0 -c:a:0 aac -map 0:a:0 -c:a:1 libopus -ac 1 -ar 16000 -b:a 8K -shortest -f rtsp rtsp://localhost:$RTSP_PORT/$RTSP_PATH
    runOnDemandRestart: yes
```
```
paths:
  camera1:
    runOnDemand: sh -c 'while true; do ffmpeg -hide_banner -loglevel error -avoid_negative_ts make_zero -fflags +genpts+nobuffer -flags low_delay -rtsp_transport tcp -use_wallclock_as_timestamps 1 -f rtsp -stimeout 5000000 -i rtsp://$USER:$PASSWORD@$CAMERA1:554/live0 -filter:a volume=10.0 -map 0:v -c:v:0 copy -map 0:a:0 -c:a:0 aac -map 0:a:0 -c:a:1 libopus -ac 1 -ar 16000 -b:a 8K -shortest -f rtsp rtsp://localhost:$RTSP_PORT/$RTSP_PATH; sleep 5; done'
    runOnDemandRestart: yes
```

## Describe how to replicate the issue
Not entirely sure -- still trying to figure out how to reproduce the issue
